name: bwu_datagrid_examples
version: 0.1.0
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: BWU Datagrid is A Polymer.dart grid/spreadsheet element inspired by SlickGrid.
homepage: https://github.com/bwu-dart/bwu_datagrid
environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  browser: '^0.10.0+2'
  bwu_datagrid:
    path: ..
  bwu_log: ^0.1.0
  bwu_utils: '>=0.1.0 <0.2.0'
  dart_to_js_script_rewriter: '^1.0.1'
  meta: ^0.12.0
  polymer: ^1.0.0-rc.16
  polymer_interop: ^1.0.0-rc.9
  quiver: '>=0.21.3 <0.23.0'
  reflectable: ^0.5.2
  web_components: ^0.12.0

dev_dependencies:
  bwu_docker: '>=0.2.1 <0.3.0'
  bwu_webdriver:  # TODO(zoechi) re-add when upgraded to 1.0.0
    path: ../../bwu_webdriver
  bwu_docker:
    path: ../../bwu_docker
  bwu_grinder_tasks: ^0.1.1-dev
#  bwu_sparkline: '>=0.0.9 <0.1.0' # TODO(zoechi) upgrade to Polymer 1
   #path: ../bwu_sparkline
#  crypto: '>=0.9.0 <0.10.0' # for Webdriver Firefox profile settings
  grinder: '>=0.7.2 <0.9.0'
  http: '>=0.11.3 <0.12.0'
  test: '>=0.12.0 <0.13.0'
  webdriver: ^1.0.0 # TODO(zoechi) re-add
    #path: ../../dart-lang/webdriver.dart

dependency_overrides:
#  analyzer: ^0.27.2
#  reflectable: ^0.5.4

transformers:
- polymer:
    entry_points:
    - web/e01_simple.html
    - web/e02_formatters.html
    - web/e07_events.html
    - web/e14_highlighting.html
    - web/e03_editing.html
    - web/e03a_compound_editors.html
    - web/e03b_editing_with_undo.html
    - web/composite_editor_item_details.html
    - web/totals_via_data_provider.html
    - web/e04_model.html
    - web/e05_collapsing.html
    - web/e08_alternative_display.html
    - web/e09_row_reordering.html
  #    - web/e10_async_post_render.html
    - web/e11_autoheight.html
    - web/e12_fillbrowser.html
    - web/e13_get_item_sorting.html
    - web/header_row.html
    - web/checkbox_row_select.html
    - web/spreadsheet.html
    - web/grouping.html
    - web/autotooltips.html

    - test/checkbox_row_select_test.html
    - test/checkbox_row_select_testx.html

    $exclude:
    - 'web/e10_async_post_render.html'
    - 'web/e10_async_post_render.dart'

#    inline_stylesheets:
#      packages/bwu_datagrid_examples/asset/examples.css: false
#      packages/bwu_datagrid/asset/smoothness/jquery-ui-1.8.16.custom.css: false

#- test/pub_serve:
#    $include: test/**_test{.*,}.dart
#    $include: '**/*.bootstrap.initialize.dart'

- $dart2js:
    commandLineOptions: ['--trust-type-annotations', '--trust-primitives']

    $exclude:
    - 'web/e10_async_post_render.html'
    - 'web/e10_async_post_render.dart'

- dart_to_js_script_rewriter





